### ISSUE TITLE
Remove unwanted meta data from your repo.

### ISSUE THREAD

**Issue by jelkner** [AntoanNikolov/DEProgrammingAntoan#1]
MacOS litters the file system with GUI meta data, creating a ``.DS_Store`` directory wherever it goes.  Please add a ``.gitignore`` file in the root directory of your git repo and add:
```
.DS_Store
```
to it.  Then remove all the currently present ``.DS_Store`` directories and commit your changes.  They won't be added to your repo after that.

**Comment by AntoanNikolov** [comment]
Done!
